<?php html::addCss('admin');?>
<div class="container">
	<div class="header">
		<div class="row">
			<div class="logo" href="/OnlineEducation">
				<a href="/OnlineEducation/index.php"><img class="image-title" src="../view/images/Logo.png" alt="Online Education"></a> 					
			</div>
			<div class="menu">
				<a href="#"><img class="image-title" src="../view/images/Menu_icon2.png" alt="Menu"></a>
			</div>
			<div class="homemenu">
				<a href="#home1"><img class="image-title" src="../view/images/Home_icon2.png" alt="Home"> </a>
			</div>
			<div class="learn"><a href="#home2"><img class="image-title" src="../view/images/Learn_icon.png" alt="learn"></a>
			</div>
			<div class="employment"><a href="#home3"><img class="image-title" src="../view/images/Employment_icon.png" alt="employment"></a>
			</div>
			<div class="building"><a href="#home4"><img class="image-title" src="../view/images/Our building_icon.png" alt="building"></a>
			</div>
			<div class="contact"><a href="#home5"><img class="image-title" src="../view/images/Contact us_icon.png" alt="Contact Us"></a>
			</div>
			<div class="right-bar">
				
			</div>
			<div class="center-bar">
				
			</div>
		</div>
	</div>
</div>
