<?php html::addCss('register');?>
<div class="overlay">
<a class="CloseImg" title="Back" ></a>
	<form name="input" action="" class="register-frm" method="POST" >
			<h1> فرم عضویت در سایت</h1>
			<h4> پر کردن فیلدهای ستاره دار (*) اجباری می باشد.</h1>
			<div class="bt-field">
				<div class="bt-input">
					<div class="bt-input">
						نام کاربری* <input id="username" type="text" value="" placeholder="نام کاربری انتخابی شما" name="username" required pattern="[a-zA-Z0-9_-]{6,12}" title="نام کاربری باید بین ۵ تا ۱۲ حرف باشد" autofocus >
					</div>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					<div class="bt-input">
						نام* <input id="input-name" type="text" value="" placeholder="نام" name="name" required>
					</div>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					نام خانوادگی* <input id="input-family" type="text" value="" placeholder="نام خانوادگی" name="family" required>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					کد ملی* <input id="input-mellicode" type="text" value=""  name="MelliCode" required>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					جنسیت <input id="input-gender" type="text" value=""  name="Gender" >
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					تاریخ تولد <input id="input-birthdate" pattern="(0[1-9]|1[0-9]|2[0-9]|3[01]).(0[1-9]|1[012]).[0-9]{4}" type="text" value="" placeholder="DD.MM.YYYY" name="BirthDate" >
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					رمز عبور* <input id="input-password" type="password" value="" placeholder="******" name="password1" alt="password" required>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					تکرار رمز عبور* <input id="input-password" type="password" value="" placeholder="******" name="password2" alt="password" required>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					پست الکترونیک* <input id="input-email" type="text" value="" placeholder="Example@domain.com" name="Email" required>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					تلفن همراه <input id="input-mobile" pattern="[0-9]{11}" type="text" value="" placeholder="09xxxxxxxxx"  name="Mobile" required>
				</div>
			</div>
			<div class="bt-field">
				<div class="bt-input">
					نشانی <input id="input-address" type="text" value=""  name="Address" required>
				</div>
				<input type="submit" name="Submit" class="bt-buttonsubmit" onclick="" value="">
			</div>
			
	</form>
</div>
